sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "pypy-5.4.1"

install:
  - python setup.py install

script:
  - nosetests ztag
  - ztag -t

notifications:
  email:
  - team@censys.io
  slack:
    secure: gLiX4zUhlYMJ0l7kJlb5Wf5CmAynj+WQufThSBPP7XlLZddl6Vql72sJuqwl1ZV75xEsqP05QDulBMJc9AaED7BP53vhngHHgWLwjt026ne5sbA/s98U735jT/qwwFvKWBCYPZ5BQdTmJO3KCyuBJH+tQnptiolog9abksG1WZk=
